### ISSUE TITLE
VS Code 通过跳板机访问远程服务器

### ISSUE THREAD

**Issue by lvjiangbinOTA** [maokelong/CSDN-maokelong95#1]
你好，通过阅读您的文章我也尝试了，但是依然没有成功。
配置如下图：
![image](https://user-images.githubusercontent.com/53812909/63069835-443fe000-bf4b-11e9-8850-a7d2121bc8a9.png)
报错如下：
![image](https://user-images.githubusercontent.com/53812909/63069860-6fc2ca80-bf4b-11e9-9e32-11cdd2466541.png)
烦请指正。
已经在博客下给您留言。

**Comment by maokelong** [comment]
看一下 S2 步骤上传的是公钥不，目录权限对不，如果还不行，就不知道问题出在哪里了。
 




------------------ Original ------------------

**Comment by maokelong** [comment]
VSCode 无法神奇地在 Server 端运行，必须在 SSH 后在 Server 下载相应组件才可以。
如果你主力机无法连接外网，或者 wget 指令无法访问外网，就可能会导致这种问题。


------------------ Original ------------------

**Comment by lvjiangbinOTA** [comment]
我用xshell6 密钥方式可以连接跳板机。跳板机和主力机再同一局域网。密钥方式登录进跳板机  然后跳板机选择主力机机器，直接连接主力机的。然后部署什么的都是再主力机上完成。主力机连接外网了的是我们的主服务器。

**Comment by maokelong** [comment]
那就不清楚了... 可以先试着不用密钥，而是密码，的方式登录。先行排除是否是密钥相关的设置不对。
如果再不行，我就不清楚了，网络这里不是我的专精方向。


------------------ Original ------------------
